### ISSUE TITLE
When integrating the addon I get a build error

### ISSUE THREAD

**Issue by beatle01** [cuba-platform/emailtemplate-addon#1]
Hi,

When integrating the addon I get following build error:

```
:app-web-toolkit:buildWidgetSet FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app-web-toolkit:buildWidgetSet'.
> A problem occurred starting process 'command 'C:\Program Files\Java\jdk1.8.0_121\bin\java.exe''
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 15s
28 actionable tasks: 5 executed, 23 up-to-date
[15:16:07.607] Task 'deploy, start' failed
java.io.IOException: CreateProcess error=206, The file name or -extension is too long
```

It seems related to the widget extension I need in my project. The demo project provided works fine.

This is the AppWidgetSet.gwt.xml:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<module>
    <inherits name="com.haulmont.cuba.web.toolkit.ui.WidgetSet" />
    <inherits name="com.haulmont.charts.web.toolkit.ui.ChartsWidgetSet" />
    <inherits name="fi.jasoft.qrcode.QrcodeWidgetset" />
</module>
```

The addon may not allow for the toolkit extension? Or there is a name that gets too long (see error) but I'm unable to identify the source of this error.

Any ideas?
-b

**Comment by petersonbr** [comment]
@beatle01 

Does your workspace location have a long path or spaces? For example:
"C:\Java\My Workspace\project" or "C:\Folder1\Folder2\Folder3\Folder4\workspace\project"

Try removing spaces from the path or changing its location.

**Comment by zaharchenko-evgeny** [comment]
Hi @beatle01,

Have you tried to reduce the project location path? Was it helped?
