### ISSUE TITLE
Error sending email

### ISSUE THREAD

**Issue by petersonbr** [cuba-platform/emailtemplate-addon#16]
There is an error on class com.haulmont.addon.emailtemplates.emailer.Emailer (method loadEmailsToSend).
Error: MetaClass not found for email$SendingMessage

The problem is in "select sm from email$SendingMessage sm". I changed it to "select sm from emailtemplates$ExtendedSendingMessage sm" and now it works.

**Comment by zaharchenko-evgeny** [comment]
Hi, the fix will be included in next addon release
