### ISSUE TITLE
I would like to list all records of the table in the database

### ISSUE THREAD

**Issue by selimabatay** [cuba-platform/emailtemplate-addon#19]
I would like to list all records of the table in the database. add a list of assets as a parameter. But I didn't find out how to show it on the html side. For example, how can I list the customer name and last name on the html side for a table that records customers.

**Comment by zaharchenko-evgeny** [comment]
Hi @selimabatay,

Please ask this question on CUBA forum https://www.cuba-platform.com/discuss/

Regards,
Evgeny
