### ISSUE TITLE
Add support for Oracle Database

### ISSUE THREAD

**Issue by petersonbr** [cuba-platform/emailtemplate-addon#2]
The component don't have oracle database scripts.

It is not possible to use in a project either, because the generated scripts are incorrect (missing fields like DTYPE in table EMAILTEMPLATES_EMAIL_TEMPLATE, for example).

Some tables (like EMAILTEMPLATES_EMAIL_TEMPLATE_FILE_DESCRIPTOR_LINK) will have to be renamed, because Oracle DB limit object names to 30 characters.

**Comment by zaharchenko-evgeny** [comment]
Hi, 

Thank you for oracle database scripts. We have merged your pull request.
