### ISSUE TITLE
Upgrade add-on to CUBA 7.1 

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/emailtemplate-addon#24]
Upgrade add-on to CUBA 7.1 platform version.
Snapshot add-on version should be updated to 1.2.
Current `releases/cuba_7.0` branch should be merged from the master. Create this branch if it does not exist.

**Comment by alx-mag** [comment]
**BEFORE RELEASE**
This addon has a dependency on [GrapesJS addon](https://github.com/cuba-platform/grapesjs-addon) `v0.2.0`. After the **GrapesJS** `v0.3.0` released this should be included in build file instead of `v0.2.0` one.
