### ISSUE TITLE
Add predefined roles

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/emailtemplate-addon#32]
### Environment

- Platform version: 7.2.x
- Addon version: 3.2.x

### Description

Create predefined system roles

**Comment by dmakagonova** [comment]
Cuba 7.2.4, Addon 1.4-SNAPSHOT

1. Create a user
2. Add a role Email templates admin
3. Click Ok
4. Log in as the created user
5. Click Administration -> Email templates
6. Click Blocks

Expected result: Blocks screen
Actual result: error
[email error.txt](https://github.com/cuba-platform/emailtemplate-addon/files/4538546/email.error.txt)
