### ISSUE TITLE
Create add-on credits file

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/emailtemplate-addon#33]
### Description 
Create information about Software Components file
https://doc.cuba-platform.com/manual-7.2/credits.html

**Comment by dmakagonova** [comment]
Cuba 7.2.4, addon 1.4-SNAPSHOT

1. Run demo/ addon 
2. Login as admin
3. Click Administration -> Help

Expected result: Help screen
Actuall result: java.lang.IllegalStateException: License text for bsd-3 not found
[licence error.txt](https://github.com/cuba-platform/emailtemplate-addon/files/4539857/licence.error.txt)
