### ISSUE TITLE
Вlank body isn’t saved after cleaning

### ISSUE THREAD

**Issue by zhenyazb** [cuba-platform/emailtemplate-addon#6]
CUBA 7.0.0
Add-on 0.3-SNAPSHOT

1. Open *Email templates* browser
2. Click *Create* - > *From designer*
3. Set *Name*, *Code*
4. Move one or more elements on body (except *1 Column* and *Tabs* )
5. Click button for cleaning the canvas
6. Click *OK* in the dialog
7. Click *OK*
8. Select the template in the list
9. Click *Edit*

Expected result: body of the template is blank
Actual result: body contains elements added on step 4

Sometimes expected result is true for elements *1 Column* and *Tabs*.

**Comment by zaharchenko-evgeny** [comment]
Related to https://github.com/cuba-platform/grapesjs-addon/issues/3

**Comment by zhenyazb** [comment]
Issue is still actual
