### ISSUE TITLE
User is not allowed to create a template with the code of the delated template

### ISSUE THREAD

**Issue by zhenyazb** [cuba-platform/emailtemplate-addon#7]
CUBA 7.0.0
Add-on 0.3-SNAPSHOT

Create and delete a template
1. Open *Email templates* browser
2. Click *Create* - > *From designer*/*From report*
3. Set *Name* and *Code*
4. Click *OK*
5. Select the template in the list
6. Click *Remove*
7. Click *OK*

Create a new template
1. Click *Create* -> *From designer*/*From report*
2. Set *Name*
3. Set the same *Code* as in the deleted template

Expected result: the template is created
Actual result: the template is not created, message \"A template with the same code already exists"

**Comment by zaharchenko-evgeny** [comment]
It is a known issue for HSQL database index
